import {
  ActivityIcon,
  BarChart3Icon,
  BugIcon,
  BotIcon,
  ChartColumnIncreasingIcon,
  ClapperboardIcon,
  DollarSign,
  FolderClosedIcon,
  GaugeIcon,
  GoalIcon,
  KeyRoundIcon,
  MegaphoneIcon,
  MousePointerClickIcon,
  ScanSearchIcon,
  SettingsIcon,
  ShieldCheckIcon,
  RouteIcon,
  UsersIcon,
  WorkflowIcon,
} from 'lucide-react'

export const navigationIcons = {
  dashboard: GaugeIcon,
  projects: FolderClosedIcon,
  analytics: ChartColumnIncreasingIcon,
  events: MousePointerClickIcon,
  errors: BugIcon,
  campaigns: MegaphoneIcon,
  sessions: ActivityIcon,
  visitors: UsersIcon,
  sessionReplay: ClapperboardIcon,
  heatmaps: ScanSearchIcon,
  funnels: WorkflowIcon,
  goals: GoalIcon,
  aiInsights: BotIcon,
  reports: BarChart3Icon,
  performance: ActivityIcon,
  userJourney: RouteIcon,
  apiKeys: KeyRoundIcon,
  settings: SettingsIcon,
  members: UsersIcon,
  permissions: ShieldCheckIcon,
  workspaceSettings: SettingsIcon,
  billing: DollarSign,
} as const
