import {
  ActivityIcon,
  BarChart3Icon,
  BotIcon,
  BugIcon,
  ChartColumnIncreasingIcon,
  ChartPie,
  CircleUserRoundIcon,
  ClapperboardIcon,
  CopyIcon,
  EditIcon,
  FolderClosedIcon,
  GaugeIcon,
  GlobeIcon,
  GoalIcon,
  KeyRoundIcon,
  MegaphoneIcon,
  MousePointerClickIcon,
  ReceiptTextIcon,
  RouteIcon,
  ScanSearchIcon,
  SettingsIcon,
  ShieldCheckIcon,
  TrashIcon,
  UsersIcon,
  WorkflowIcon,
} from 'lucide-react'

export const navigationIcons = {
  dashboard: GaugeIcon,
  projects: FolderClosedIcon,
  analytics: ChartColumnIncreasingIcon,
  events: MousePointerClickIcon,
  errors: BugIcon,
  campaigns: MegaphoneIcon,
  sessions: ActivityIcon,
  visitors: UsersIcon,
  sessionReplay: ClapperboardIcon,
  heatmaps: ScanSearchIcon,
  funnels: WorkflowIcon,
  goals: GoalIcon,
  aiInsights: BotIcon,
  reports: BarChart3Icon,
  performance: ActivityIcon,
  userJourney: RouteIcon,
  apiKeys: KeyRoundIcon,
  settings: SettingsIcon,
  members: UsersIcon,
  permissions: ShieldCheckIcon,
  workspaceSettings: SettingsIcon,
  billing: ReceiptTextIcon,
  usage: ChartPie,

  // added
  workspaces: FolderClosedIcon,
  profile: CircleUserRoundIcon,
  accountSettings: SettingsIcon,
  team: UsersIcon,
  domain: GlobeIcon,
  trash: TrashIcon,
  copy: CopyIcon,
  edit: EditIcon,
} as const
