/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authPasswordResetRouteImport } from './routes/(auth)/password-reset'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAccountRouteImport } from './routes/app/account'
import { Route as AppPlansRouteImport } from './routes/app/plans'
import { Route as AppWorkspaceIndexRouteImport } from './routes/app/$workspace/index'
import { Route as AppWorkspaceProjectsIndexRouteImport } from './routes/app/$workspace/projects/index'
import { Route as AppWorkspaceProjectsProjectRouteRouteImport } from './routes/app/$workspace/projects/$project/route'
import { Route as AppWorkspaceProjectsProjectIndexRouteImport } from './routes/app/$workspace/projects/$project/index'
import { Route as AppWorkspaceProjectsProjectAiInsightsRouteImport } from './routes/app/$workspace/projects/$project/ai-insights'
import { Route as AppWorkspaceProjectsProjectAnalyticsRouteImport } from './routes/app/$workspace/projects/$project/analytics'
import { Route as AppWorkspaceProjectsProjectBillingRouteImport } from './routes/app/$workspace/projects/$project/billing'
import { Route as AppWorkspaceProjectsProjectDashboardRouteImport } from './routes/app/$workspace/projects/$project/dashboard'
import { Route as AppWorkspaceProjectsProjectEventsRouteImport } from './routes/app/$workspace/projects/$project/events'
import { Route as AppWorkspaceProjectsProjectFunnelsRouteImport } from './routes/app/$workspace/projects/$project/funnels'
import { Route as AppWorkspaceProjectsProjectGoalsRouteImport } from './routes/app/$workspace/projects/$project/goals'
import { Route as AppWorkspaceProjectsProjectInviteRouteImport } from './routes/app/$workspace/projects/$project/invite'
import { Route as AppWorkspaceProjectsProjectKeysRouteImport } from './routes/app/$workspace/projects/$project/keys'
import { Route as AppWorkspaceProjectsProjectMembersRouteImport } from './routes/app/$workspace/projects/$project/members'
import { Route as AppWorkspaceProjectsProjectPerformanceRouteImport } from './routes/app/$workspace/projects/$project/performance'
import { Route as AppWorkspaceProjectsProjectPermissionProfilesRouteImport } from './routes/app/$workspace/projects/$project/permission-profiles'
import { Route as AppWorkspaceProjectsProjectReportsRouteImport } from './routes/app/$workspace/projects/$project/reports'
import { Route as AppWorkspaceProjectsProjectSessionReplayRouteImport } from './routes/app/$workspace/projects/$project/session-replay'
import { Route as AppWorkspaceProjectsProjectSettingsRouteImport } from './routes/app/$workspace/projects/$project/settings'
import { Route as AppWorkspaceProjectsProjectVisitorsRouteImport } from './routes/app/$workspace/projects/$project/visitors'
import { Route as AppWorkspaceProjectsProjectWorkspaceSettingsRouteImport } from './routes/app/$workspace/projects/$project/workspace-settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authPasswordResetRoute = authPasswordResetRouteImport.update({
  id: '/password-reset',
  path: '/password-reset',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPlansRoute = AppPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkspaceIndexRoute = AppWorkspaceIndexRouteImport.update({
  id: '/$workspace/',
  path: '/$workspace/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkspaceProjectsIndexRoute =
  AppWorkspaceProjectsIndexRouteImport.update({
    id: '/$workspace/projects/',
    path: '/$workspace/projects/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppWorkspaceProjectsProjectRouteRoute =
  AppWorkspaceProjectsProjectRouteRouteImport.update({
    id: '/$workspace/projects/$project',
    path: '/$workspace/projects/$project',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppWorkspaceProjectsProjectIndexRoute =
  AppWorkspaceProjectsProjectIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppWorkspaceProjectsProjectRouteRoute,
  } as any)
const AppWorkspaceProjectsProjectAiInsightsRoute =
  AppWorkspaceProjectsProjectAiInsightsRouteImport.update({
    id: '/ai-insights',
    path: '/ai-insights',
    getParentRoute: () => AppWorkspaceProjectsProjectRouteRoute,
  } as any)
const AppWorkspaceProjectsProjectAnalyticsRoute =
  AppWorkspaceProjectsProjectAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AppWorkspaceProjectsProjectRouteRoute,
  } as any)
const AppWorkspaceProjectsProjectBillingRoute =
  AppWorkspaceProjectsProjectBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AppWorkspaceProjectsProjectRouteRoute,
  } as any)
const AppWorkspaceProjectsProjectDashboardRoute =
  AppWorkspaceProjectsProjectDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AppWorkspaceProjectsProjectRouteRoute,
  } as any)
const AppWorkspaceProjectsProjectEventsRoute =
  AppWorkspaceProjectsProjectEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AppWorkspaceProjectsProjectRouteRoute,
  } as any)
const AppWorkspaceProjectsProjectFunnelsRoute =
  AppWorkspaceProjectsProjectFunnelsRouteImport.update({
    id: '/funnels',
    path: '/funnels',
    getParentRoute: () => AppWorkspaceProjectsProjectRouteRoute,
  } as any)
const AppWorkspaceProjectsProjectGoalsRoute =
  AppWorkspaceProjectsProjectGoalsRouteImport.update({
    id: '/goals',
    path: '/goals',
    getParentRoute: () => AppWorkspaceProjectsProjectRouteRoute,
  } as any)
const AppWorkspaceProjectsProjectInviteRoute =
  AppWorkspaceProjectsProjectInviteRouteImport.update({
    id: '/invite',
    path: '/invite',
    getParentRoute: () => AppWorkspaceProjectsProjectRouteRoute,
  } as any)
const AppWorkspaceProjectsProjectKeysRoute =
  AppWorkspaceProjectsProjectKeysRouteImport.update({
    id: '/keys',
    path: '/keys',
    getParentRoute: () => AppWorkspaceProjectsProjectRouteRoute,
  } as any)
const AppWorkspaceProjectsProjectMembersRoute =
  AppWorkspaceProjectsProjectMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AppWorkspaceProjectsProjectRouteRoute,
  } as any)
const AppWorkspaceProjectsProjectPerformanceRoute =
  AppWorkspaceProjectsProjectPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AppWorkspaceProjectsProjectRouteRoute,
  } as any)
const AppWorkspaceProjectsProjectPermissionProfilesRoute =
  AppWorkspaceProjectsProjectPermissionProfilesRouteImport.update({
    id: '/permission-profiles',
    path: '/permission-profiles',
    getParentRoute: () => AppWorkspaceProjectsProjectRouteRoute,
  } as any)
const AppWorkspaceProjectsProjectReportsRoute =
  AppWorkspaceProjectsProjectReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AppWorkspaceProjectsProjectRouteRoute,
  } as any)
const AppWorkspaceProjectsProjectSessionReplayRoute =
  AppWorkspaceProjectsProjectSessionReplayRouteImport.update({
    id: '/session-replay',
    path: '/session-replay',
    getParentRoute: () => AppWorkspaceProjectsProjectRouteRoute,
  } as any)
const AppWorkspaceProjectsProjectSettingsRoute =
  AppWorkspaceProjectsProjectSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppWorkspaceProjectsProjectRouteRoute,
  } as any)
const AppWorkspaceProjectsProjectVisitorsRoute =
  AppWorkspaceProjectsProjectVisitorsRouteImport.update({
    id: '/visitors',
    path: '/visitors',
    getParentRoute: () => AppWorkspaceProjectsProjectRouteRoute,
  } as any)
const AppWorkspaceProjectsProjectWorkspaceSettingsRoute =
  AppWorkspaceProjectsProjectWorkspaceSettingsRouteImport.update({
    id: '/workspace-settings',
    path: '/workspace-settings',
    getParentRoute: () => AppWorkspaceProjectsProjectRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/password-reset': typeof authPasswordResetRoute
  '/sign-up': typeof authSignUpRoute
  '/app/account': typeof AppAccountRoute
  '/app/plans': typeof AppPlansRoute
  '/app/': typeof AppIndexRoute
  '/app/$workspace/': typeof AppWorkspaceIndexRoute
  '/app/$workspace/projects/$project': typeof AppWorkspaceProjectsProjectRouteRouteWithChildren
  '/app/$workspace/projects/': typeof AppWorkspaceProjectsIndexRoute
  '/app/$workspace/projects/$project/ai-insights': typeof AppWorkspaceProjectsProjectAiInsightsRoute
  '/app/$workspace/projects/$project/analytics': typeof AppWorkspaceProjectsProjectAnalyticsRoute
  '/app/$workspace/projects/$project/billing': typeof AppWorkspaceProjectsProjectBillingRoute
  '/app/$workspace/projects/$project/dashboard': typeof AppWorkspaceProjectsProjectDashboardRoute
  '/app/$workspace/projects/$project/events': typeof AppWorkspaceProjectsProjectEventsRoute
  '/app/$workspace/projects/$project/funnels': typeof AppWorkspaceProjectsProjectFunnelsRoute
  '/app/$workspace/projects/$project/goals': typeof AppWorkspaceProjectsProjectGoalsRoute
  '/app/$workspace/projects/$project/invite': typeof AppWorkspaceProjectsProjectInviteRoute
  '/app/$workspace/projects/$project/keys': typeof AppWorkspaceProjectsProjectKeysRoute
  '/app/$workspace/projects/$project/members': typeof AppWorkspaceProjectsProjectMembersRoute
  '/app/$workspace/projects/$project/performance': typeof AppWorkspaceProjectsProjectPerformanceRoute
  '/app/$workspace/projects/$project/permission-profiles': typeof AppWorkspaceProjectsProjectPermissionProfilesRoute
  '/app/$workspace/projects/$project/reports': typeof AppWorkspaceProjectsProjectReportsRoute
  '/app/$workspace/projects/$project/session-replay': typeof AppWorkspaceProjectsProjectSessionReplayRoute
  '/app/$workspace/projects/$project/settings': typeof AppWorkspaceProjectsProjectSettingsRoute
  '/app/$workspace/projects/$project/visitors': typeof AppWorkspaceProjectsProjectVisitorsRoute
  '/app/$workspace/projects/$project/workspace-settings': typeof AppWorkspaceProjectsProjectWorkspaceSettingsRoute
  '/app/$workspace/projects/$project/': typeof AppWorkspaceProjectsProjectIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/password-reset': typeof authPasswordResetRoute
  '/sign-up': typeof authSignUpRoute
  '/app/account': typeof AppAccountRoute
  '/app/plans': typeof AppPlansRoute
  '/app': typeof AppIndexRoute
  '/app/$workspace': typeof AppWorkspaceIndexRoute
  '/app/$workspace/projects': typeof AppWorkspaceProjectsIndexRoute
  '/app/$workspace/projects/$project/ai-insights': typeof AppWorkspaceProjectsProjectAiInsightsRoute
  '/app/$workspace/projects/$project/analytics': typeof AppWorkspaceProjectsProjectAnalyticsRoute
  '/app/$workspace/projects/$project/billing': typeof AppWorkspaceProjectsProjectBillingRoute
  '/app/$workspace/projects/$project/dashboard': typeof AppWorkspaceProjectsProjectDashboardRoute
  '/app/$workspace/projects/$project/events': typeof AppWorkspaceProjectsProjectEventsRoute
  '/app/$workspace/projects/$project/funnels': typeof AppWorkspaceProjectsProjectFunnelsRoute
  '/app/$workspace/projects/$project/goals': typeof AppWorkspaceProjectsProjectGoalsRoute
  '/app/$workspace/projects/$project/invite': typeof AppWorkspaceProjectsProjectInviteRoute
  '/app/$workspace/projects/$project/keys': typeof AppWorkspaceProjectsProjectKeysRoute
  '/app/$workspace/projects/$project/members': typeof AppWorkspaceProjectsProjectMembersRoute
  '/app/$workspace/projects/$project/performance': typeof AppWorkspaceProjectsProjectPerformanceRoute
  '/app/$workspace/projects/$project/permission-profiles': typeof AppWorkspaceProjectsProjectPermissionProfilesRoute
  '/app/$workspace/projects/$project/reports': typeof AppWorkspaceProjectsProjectReportsRoute
  '/app/$workspace/projects/$project/session-replay': typeof AppWorkspaceProjectsProjectSessionReplayRoute
  '/app/$workspace/projects/$project/settings': typeof AppWorkspaceProjectsProjectSettingsRoute
  '/app/$workspace/projects/$project/visitors': typeof AppWorkspaceProjectsProjectVisitorsRoute
  '/app/$workspace/projects/$project/workspace-settings': typeof AppWorkspaceProjectsProjectWorkspaceSettingsRoute
  '/app/$workspace/projects/$project': typeof AppWorkspaceProjectsProjectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/password-reset': typeof authPasswordResetRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/app/account': typeof AppAccountRoute
  '/app/plans': typeof AppPlansRoute
  '/app/': typeof AppIndexRoute
  '/app/$workspace/': typeof AppWorkspaceIndexRoute
  '/app/$workspace/projects/$project': typeof AppWorkspaceProjectsProjectRouteRouteWithChildren
  '/app/$workspace/projects/': typeof AppWorkspaceProjectsIndexRoute
  '/app/$workspace/projects/$project/ai-insights': typeof AppWorkspaceProjectsProjectAiInsightsRoute
  '/app/$workspace/projects/$project/analytics': typeof AppWorkspaceProjectsProjectAnalyticsRoute
  '/app/$workspace/projects/$project/billing': typeof AppWorkspaceProjectsProjectBillingRoute
  '/app/$workspace/projects/$project/dashboard': typeof AppWorkspaceProjectsProjectDashboardRoute
  '/app/$workspace/projects/$project/events': typeof AppWorkspaceProjectsProjectEventsRoute
  '/app/$workspace/projects/$project/funnels': typeof AppWorkspaceProjectsProjectFunnelsRoute
  '/app/$workspace/projects/$project/goals': typeof AppWorkspaceProjectsProjectGoalsRoute
  '/app/$workspace/projects/$project/invite': typeof AppWorkspaceProjectsProjectInviteRoute
  '/app/$workspace/projects/$project/keys': typeof AppWorkspaceProjectsProjectKeysRoute
  '/app/$workspace/projects/$project/members': typeof AppWorkspaceProjectsProjectMembersRoute
  '/app/$workspace/projects/$project/performance': typeof AppWorkspaceProjectsProjectPerformanceRoute
  '/app/$workspace/projects/$project/permission-profiles': typeof AppWorkspaceProjectsProjectPermissionProfilesRoute
  '/app/$workspace/projects/$project/reports': typeof AppWorkspaceProjectsProjectReportsRoute
  '/app/$workspace/projects/$project/session-replay': typeof AppWorkspaceProjectsProjectSessionReplayRoute
  '/app/$workspace/projects/$project/settings': typeof AppWorkspaceProjectsProjectSettingsRoute
  '/app/$workspace/projects/$project/visitors': typeof AppWorkspaceProjectsProjectVisitorsRoute
  '/app/$workspace/projects/$project/workspace-settings': typeof AppWorkspaceProjectsProjectWorkspaceSettingsRoute
  '/app/$workspace/projects/$project/': typeof AppWorkspaceProjectsProjectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/password-reset'
    | '/sign-up'
    | '/app/account'
    | '/app/plans'
    | '/app/'
    | '/app/$workspace/'
    | '/app/$workspace/projects/$project'
    | '/app/$workspace/projects/'
    | '/app/$workspace/projects/$project/ai-insights'
    | '/app/$workspace/projects/$project/analytics'
    | '/app/$workspace/projects/$project/billing'
    | '/app/$workspace/projects/$project/dashboard'
    | '/app/$workspace/projects/$project/events'
    | '/app/$workspace/projects/$project/funnels'
    | '/app/$workspace/projects/$project/goals'
    | '/app/$workspace/projects/$project/invite'
    | '/app/$workspace/projects/$project/keys'
    | '/app/$workspace/projects/$project/members'
    | '/app/$workspace/projects/$project/performance'
    | '/app/$workspace/projects/$project/permission-profiles'
    | '/app/$workspace/projects/$project/reports'
    | '/app/$workspace/projects/$project/session-replay'
    | '/app/$workspace/projects/$project/settings'
    | '/app/$workspace/projects/$project/visitors'
    | '/app/$workspace/projects/$project/workspace-settings'
    | '/app/$workspace/projects/$project/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/password-reset'
    | '/sign-up'
    | '/app/account'
    | '/app/plans'
    | '/app'
    | '/app/$workspace'
    | '/app/$workspace/projects'
    | '/app/$workspace/projects/$project/ai-insights'
    | '/app/$workspace/projects/$project/analytics'
    | '/app/$workspace/projects/$project/billing'
    | '/app/$workspace/projects/$project/dashboard'
    | '/app/$workspace/projects/$project/events'
    | '/app/$workspace/projects/$project/funnels'
    | '/app/$workspace/projects/$project/goals'
    | '/app/$workspace/projects/$project/invite'
    | '/app/$workspace/projects/$project/keys'
    | '/app/$workspace/projects/$project/members'
    | '/app/$workspace/projects/$project/performance'
    | '/app/$workspace/projects/$project/permission-profiles'
    | '/app/$workspace/projects/$project/reports'
    | '/app/$workspace/projects/$project/session-replay'
    | '/app/$workspace/projects/$project/settings'
    | '/app/$workspace/projects/$project/visitors'
    | '/app/$workspace/projects/$project/workspace-settings'
    | '/app/$workspace/projects/$project'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/app'
    | '/(auth)/login'
    | '/(auth)/password-reset'
    | '/(auth)/sign-up'
    | '/app/account'
    | '/app/plans'
    | '/app/'
    | '/app/$workspace/'
    | '/app/$workspace/projects/$project'
    | '/app/$workspace/projects/'
    | '/app/$workspace/projects/$project/ai-insights'
    | '/app/$workspace/projects/$project/analytics'
    | '/app/$workspace/projects/$project/billing'
    | '/app/$workspace/projects/$project/dashboard'
    | '/app/$workspace/projects/$project/events'
    | '/app/$workspace/projects/$project/funnels'
    | '/app/$workspace/projects/$project/goals'
    | '/app/$workspace/projects/$project/invite'
    | '/app/$workspace/projects/$project/keys'
    | '/app/$workspace/projects/$project/members'
    | '/app/$workspace/projects/$project/performance'
    | '/app/$workspace/projects/$project/permission-profiles'
    | '/app/$workspace/projects/$project/reports'
    | '/app/$workspace/projects/$project/session-replay'
    | '/app/$workspace/projects/$project/settings'
    | '/app/$workspace/projects/$project/visitors'
    | '/app/$workspace/projects/$project/workspace-settings'
    | '/app/$workspace/projects/$project/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/password-reset': {
      id: '/(auth)/password-reset'
      path: '/password-reset'
      fullPath: '/password-reset'
      preLoaderRoute: typeof authPasswordResetRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/plans': {
      id: '/app/plans'
      path: '/plans'
      fullPath: '/app/plans'
      preLoaderRoute: typeof AppPlansRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/$workspace/': {
      id: '/app/$workspace/'
      path: '/$workspace'
      fullPath: '/app/$workspace/'
      preLoaderRoute: typeof AppWorkspaceIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/$workspace/projects/': {
      id: '/app/$workspace/projects/'
      path: '/$workspace/projects'
      fullPath: '/app/$workspace/projects/'
      preLoaderRoute: typeof AppWorkspaceProjectsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/$workspace/projects/$project': {
      id: '/app/$workspace/projects/$project'
      path: '/$workspace/projects/$project'
      fullPath: '/app/$workspace/projects/$project'
      preLoaderRoute: typeof AppWorkspaceProjectsProjectRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/$workspace/projects/$project/': {
      id: '/app/$workspace/projects/$project/'
      path: '/'
      fullPath: '/app/$workspace/projects/$project/'
      preLoaderRoute: typeof AppWorkspaceProjectsProjectIndexRouteImport
      parentRoute: typeof AppWorkspaceProjectsProjectRouteRoute
    }
    '/app/$workspace/projects/$project/ai-insights': {
      id: '/app/$workspace/projects/$project/ai-insights'
      path: '/ai-insights'
      fullPath: '/app/$workspace/projects/$project/ai-insights'
      preLoaderRoute: typeof AppWorkspaceProjectsProjectAiInsightsRouteImport
      parentRoute: typeof AppWorkspaceProjectsProjectRouteRoute
    }
    '/app/$workspace/projects/$project/analytics': {
      id: '/app/$workspace/projects/$project/analytics'
      path: '/analytics'
      fullPath: '/app/$workspace/projects/$project/analytics'
      preLoaderRoute: typeof AppWorkspaceProjectsProjectAnalyticsRouteImport
      parentRoute: typeof AppWorkspaceProjectsProjectRouteRoute
    }
    '/app/$workspace/projects/$project/billing': {
      id: '/app/$workspace/projects/$project/billing'
      path: '/billing'
      fullPath: '/app/$workspace/projects/$project/billing'
      preLoaderRoute: typeof AppWorkspaceProjectsProjectBillingRouteImport
      parentRoute: typeof AppWorkspaceProjectsProjectRouteRoute
    }
    '/app/$workspace/projects/$project/dashboard': {
      id: '/app/$workspace/projects/$project/dashboard'
      path: '/dashboard'
      fullPath: '/app/$workspace/projects/$project/dashboard'
      preLoaderRoute: typeof AppWorkspaceProjectsProjectDashboardRouteImport
      parentRoute: typeof AppWorkspaceProjectsProjectRouteRoute
    }
    '/app/$workspace/projects/$project/events': {
      id: '/app/$workspace/projects/$project/events'
      path: '/events'
      fullPath: '/app/$workspace/projects/$project/events'
      preLoaderRoute: typeof AppWorkspaceProjectsProjectEventsRouteImport
      parentRoute: typeof AppWorkspaceProjectsProjectRouteRoute
    }
    '/app/$workspace/projects/$project/funnels': {
      id: '/app/$workspace/projects/$project/funnels'
      path: '/funnels'
      fullPath: '/app/$workspace/projects/$project/funnels'
      preLoaderRoute: typeof AppWorkspaceProjectsProjectFunnelsRouteImport
      parentRoute: typeof AppWorkspaceProjectsProjectRouteRoute
    }
    '/app/$workspace/projects/$project/goals': {
      id: '/app/$workspace/projects/$project/goals'
      path: '/goals'
      fullPath: '/app/$workspace/projects/$project/goals'
      preLoaderRoute: typeof AppWorkspaceProjectsProjectGoalsRouteImport
      parentRoute: typeof AppWorkspaceProjectsProjectRouteRoute
    }
    '/app/$workspace/projects/$project/invite': {
      id: '/app/$workspace/projects/$project/invite'
      path: '/invite'
      fullPath: '/app/$workspace/projects/$project/invite'
      preLoaderRoute: typeof AppWorkspaceProjectsProjectInviteRouteImport
      parentRoute: typeof AppWorkspaceProjectsProjectRouteRoute
    }
    '/app/$workspace/projects/$project/keys': {
      id: '/app/$workspace/projects/$project/keys'
      path: '/keys'
      fullPath: '/app/$workspace/projects/$project/keys'
      preLoaderRoute: typeof AppWorkspaceProjectsProjectKeysRouteImport
      parentRoute: typeof AppWorkspaceProjectsProjectRouteRoute
    }
    '/app/$workspace/projects/$project/members': {
      id: '/app/$workspace/projects/$project/members'
      path: '/members'
      fullPath: '/app/$workspace/projects/$project/members'
      preLoaderRoute: typeof AppWorkspaceProjectsProjectMembersRouteImport
      parentRoute: typeof AppWorkspaceProjectsProjectRouteRoute
    }
    '/app/$workspace/projects/$project/performance': {
      id: '/app/$workspace/projects/$project/performance'
      path: '/performance'
      fullPath: '/app/$workspace/projects/$project/performance'
      preLoaderRoute: typeof AppWorkspaceProjectsProjectPerformanceRouteImport
      parentRoute: typeof AppWorkspaceProjectsProjectRouteRoute
    }
    '/app/$workspace/projects/$project/permission-profiles': {
      id: '/app/$workspace/projects/$project/permission-profiles'
      path: '/permission-profiles'
      fullPath: '/app/$workspace/projects/$project/permission-profiles'
      preLoaderRoute: typeof AppWorkspaceProjectsProjectPermissionProfilesRouteImport
      parentRoute: typeof AppWorkspaceProjectsProjectRouteRoute
    }
    '/app/$workspace/projects/$project/reports': {
      id: '/app/$workspace/projects/$project/reports'
      path: '/reports'
      fullPath: '/app/$workspace/projects/$project/reports'
      preLoaderRoute: typeof AppWorkspaceProjectsProjectReportsRouteImport
      parentRoute: typeof AppWorkspaceProjectsProjectRouteRoute
    }
    '/app/$workspace/projects/$project/session-replay': {
      id: '/app/$workspace/projects/$project/session-replay'
      path: '/session-replay'
      fullPath: '/app/$workspace/projects/$project/session-replay'
      preLoaderRoute: typeof AppWorkspaceProjectsProjectSessionReplayRouteImport
      parentRoute: typeof AppWorkspaceProjectsProjectRouteRoute
    }
    '/app/$workspace/projects/$project/settings': {
      id: '/app/$workspace/projects/$project/settings'
      path: '/settings'
      fullPath: '/app/$workspace/projects/$project/settings'
      preLoaderRoute: typeof AppWorkspaceProjectsProjectSettingsRouteImport
      parentRoute: typeof AppWorkspaceProjectsProjectRouteRoute
    }
    '/app/$workspace/projects/$project/visitors': {
      id: '/app/$workspace/projects/$project/visitors'
      path: '/visitors'
      fullPath: '/app/$workspace/projects/$project/visitors'
      preLoaderRoute: typeof AppWorkspaceProjectsProjectVisitorsRouteImport
      parentRoute: typeof AppWorkspaceProjectsProjectRouteRoute
    }
    '/app/$workspace/projects/$project/workspace-settings': {
      id: '/app/$workspace/projects/$project/workspace-settings'
      path: '/workspace-settings'
      fullPath: '/app/$workspace/projects/$project/workspace-settings'
      preLoaderRoute: typeof AppWorkspaceProjectsProjectWorkspaceSettingsRouteImport
      parentRoute: typeof AppWorkspaceProjectsProjectRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authPasswordResetRoute: typeof authPasswordResetRoute
  authSignUpRoute: typeof authSignUpRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authPasswordResetRoute: authPasswordResetRoute,
  authSignUpRoute: authSignUpRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AppWorkspaceProjectsProjectRouteRouteChildren {
  AppWorkspaceProjectsProjectAiInsightsRoute: typeof AppWorkspaceProjectsProjectAiInsightsRoute
  AppWorkspaceProjectsProjectAnalyticsRoute: typeof AppWorkspaceProjectsProjectAnalyticsRoute
  AppWorkspaceProjectsProjectBillingRoute: typeof AppWorkspaceProjectsProjectBillingRoute
  AppWorkspaceProjectsProjectDashboardRoute: typeof AppWorkspaceProjectsProjectDashboardRoute
  AppWorkspaceProjectsProjectEventsRoute: typeof AppWorkspaceProjectsProjectEventsRoute
  AppWorkspaceProjectsProjectFunnelsRoute: typeof AppWorkspaceProjectsProjectFunnelsRoute
  AppWorkspaceProjectsProjectGoalsRoute: typeof AppWorkspaceProjectsProjectGoalsRoute
  AppWorkspaceProjectsProjectInviteRoute: typeof AppWorkspaceProjectsProjectInviteRoute
  AppWorkspaceProjectsProjectKeysRoute: typeof AppWorkspaceProjectsProjectKeysRoute
  AppWorkspaceProjectsProjectMembersRoute: typeof AppWorkspaceProjectsProjectMembersRoute
  AppWorkspaceProjectsProjectPerformanceRoute: typeof AppWorkspaceProjectsProjectPerformanceRoute
  AppWorkspaceProjectsProjectPermissionProfilesRoute: typeof AppWorkspaceProjectsProjectPermissionProfilesRoute
  AppWorkspaceProjectsProjectReportsRoute: typeof AppWorkspaceProjectsProjectReportsRoute
  AppWorkspaceProjectsProjectSessionReplayRoute: typeof AppWorkspaceProjectsProjectSessionReplayRoute
  AppWorkspaceProjectsProjectSettingsRoute: typeof AppWorkspaceProjectsProjectSettingsRoute
  AppWorkspaceProjectsProjectVisitorsRoute: typeof AppWorkspaceProjectsProjectVisitorsRoute
  AppWorkspaceProjectsProjectWorkspaceSettingsRoute: typeof AppWorkspaceProjectsProjectWorkspaceSettingsRoute
  AppWorkspaceProjectsProjectIndexRoute: typeof AppWorkspaceProjectsProjectIndexRoute
}

const AppWorkspaceProjectsProjectRouteRouteChildren: AppWorkspaceProjectsProjectRouteRouteChildren =
  {
    AppWorkspaceProjectsProjectAiInsightsRoute:
      AppWorkspaceProjectsProjectAiInsightsRoute,
    AppWorkspaceProjectsProjectAnalyticsRoute:
      AppWorkspaceProjectsProjectAnalyticsRoute,
    AppWorkspaceProjectsProjectBillingRoute:
      AppWorkspaceProjectsProjectBillingRoute,
    AppWorkspaceProjectsProjectDashboardRoute:
      AppWorkspaceProjectsProjectDashboardRoute,
    AppWorkspaceProjectsProjectEventsRoute:
      AppWorkspaceProjectsProjectEventsRoute,
    AppWorkspaceProjectsProjectFunnelsRoute:
      AppWorkspaceProjectsProjectFunnelsRoute,
    AppWorkspaceProjectsProjectGoalsRoute:
      AppWorkspaceProjectsProjectGoalsRoute,
    AppWorkspaceProjectsProjectInviteRoute:
      AppWorkspaceProjectsProjectInviteRoute,
    AppWorkspaceProjectsProjectKeysRoute: AppWorkspaceProjectsProjectKeysRoute,
    AppWorkspaceProjectsProjectMembersRoute:
      AppWorkspaceProjectsProjectMembersRoute,
    AppWorkspaceProjectsProjectPerformanceRoute:
      AppWorkspaceProjectsProjectPerformanceRoute,
    AppWorkspaceProjectsProjectPermissionProfilesRoute:
      AppWorkspaceProjectsProjectPermissionProfilesRoute,
    AppWorkspaceProjectsProjectReportsRoute:
      AppWorkspaceProjectsProjectReportsRoute,
    AppWorkspaceProjectsProjectSessionReplayRoute:
      AppWorkspaceProjectsProjectSessionReplayRoute,
    AppWorkspaceProjectsProjectSettingsRoute:
      AppWorkspaceProjectsProjectSettingsRoute,
    AppWorkspaceProjectsProjectVisitorsRoute:
      AppWorkspaceProjectsProjectVisitorsRoute,
    AppWorkspaceProjectsProjectWorkspaceSettingsRoute:
      AppWorkspaceProjectsProjectWorkspaceSettingsRoute,
    AppWorkspaceProjectsProjectIndexRoute:
      AppWorkspaceProjectsProjectIndexRoute,
  }

const AppWorkspaceProjectsProjectRouteRouteWithChildren =
  AppWorkspaceProjectsProjectRouteRoute._addFileChildren(
    AppWorkspaceProjectsProjectRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppPlansRoute: typeof AppPlansRoute
  AppIndexRoute: typeof AppIndexRoute
  AppWorkspaceIndexRoute: typeof AppWorkspaceIndexRoute
  AppWorkspaceProjectsProjectRouteRoute: typeof AppWorkspaceProjectsProjectRouteRouteWithChildren
  AppWorkspaceProjectsIndexRoute: typeof AppWorkspaceProjectsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppPlansRoute: AppPlansRoute,
  AppIndexRoute: AppIndexRoute,
  AppWorkspaceIndexRoute: AppWorkspaceIndexRoute,
  AppWorkspaceProjectsProjectRouteRoute:
    AppWorkspaceProjectsProjectRouteRouteWithChildren,
  AppWorkspaceProjectsIndexRoute: AppWorkspaceProjectsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
