/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as openRouteRouteImport } from './routes/(open)/route'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as openIndexRouteImport } from './routes/(open)/index'
import { Route as openPricingRouteImport } from './routes/(open)/pricing'
import { Route as openProductsIndexRouteImport } from './routes/(open)/products/index'
import { Route as openSolutionsIndexRouteImport } from './routes/(open)/solutions/index'
import { Route as openProductsProductIdIndexRouteImport } from './routes/(open)/products/$productId/index'
import { Route as openSolutionsSolutionIdIndexRouteImport } from './routes/(open)/solutions/$solutionId/index'

const openRouteRoute = openRouteRouteImport.update({
  id: '/(open)',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const openIndexRoute = openIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => openRouteRoute,
} as any)
const openPricingRoute = openPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => openRouteRoute,
} as any)
const openProductsIndexRoute = openProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => openRouteRoute,
} as any)
const openSolutionsIndexRoute = openSolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => openRouteRoute,
} as any)
const openProductsProductIdIndexRoute =
  openProductsProductIdIndexRouteImport.update({
    id: '/products/$productId/',
    path: '/products/$productId/',
    getParentRoute: () => openRouteRoute,
  } as any)
const openSolutionsSolutionIdIndexRoute =
  openSolutionsSolutionIdIndexRouteImport.update({
    id: '/solutions/$solutionId/',
    path: '/solutions/$solutionId/',
    getParentRoute: () => openRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof authLoginRoute
  '/sign-up': typeof authSignUpRoute
  '/pricing': typeof openPricingRoute
  '/': typeof openIndexRoute
  '/products/': typeof openProductsIndexRoute
  '/solutions/': typeof openSolutionsIndexRoute
  '/products/$productId/': typeof openProductsProductIdIndexRoute
  '/solutions/$solutionId/': typeof openSolutionsSolutionIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/sign-up': typeof authSignUpRoute
  '/pricing': typeof openPricingRoute
  '/': typeof openIndexRoute
  '/products': typeof openProductsIndexRoute
  '/solutions': typeof openSolutionsIndexRoute
  '/products/$productId': typeof openProductsProductIdIndexRoute
  '/solutions/$solutionId': typeof openSolutionsSolutionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(open)': typeof openRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(open)/pricing': typeof openPricingRoute
  '/(open)/': typeof openIndexRoute
  '/(open)/products/': typeof openProductsIndexRoute
  '/(open)/solutions/': typeof openSolutionsIndexRoute
  '/(open)/products/$productId/': typeof openProductsProductIdIndexRoute
  '/(open)/solutions/$solutionId/': typeof openSolutionsSolutionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/sign-up'
    | '/pricing'
    | '/'
    | '/products/'
    | '/solutions/'
    | '/products/$productId/'
    | '/solutions/$solutionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/sign-up'
    | '/pricing'
    | '/'
    | '/products'
    | '/solutions'
    | '/products/$productId'
    | '/solutions/$solutionId'
  id:
    | '__root__'
    | '/(open)'
    | '/(auth)/login'
    | '/(auth)/sign-up'
    | '/(open)/pricing'
    | '/(open)/'
    | '/(open)/products/'
    | '/(open)/solutions/'
    | '/(open)/products/$productId/'
    | '/(open)/solutions/$solutionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  openRouteRoute: typeof openRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authSignUpRoute: typeof authSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(open)': {
      id: '/(open)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof openRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(open)/': {
      id: '/(open)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof openIndexRouteImport
      parentRoute: typeof openRouteRoute
    }
    '/(open)/pricing': {
      id: '/(open)/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof openPricingRouteImport
      parentRoute: typeof openRouteRoute
    }
    '/(open)/products/': {
      id: '/(open)/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof openProductsIndexRouteImport
      parentRoute: typeof openRouteRoute
    }
    '/(open)/solutions/': {
      id: '/(open)/solutions/'
      path: '/solutions'
      fullPath: '/solutions/'
      preLoaderRoute: typeof openSolutionsIndexRouteImport
      parentRoute: typeof openRouteRoute
    }
    '/(open)/products/$productId/': {
      id: '/(open)/products/$productId/'
      path: '/products/$productId'
      fullPath: '/products/$productId/'
      preLoaderRoute: typeof openProductsProductIdIndexRouteImport
      parentRoute: typeof openRouteRoute
    }
    '/(open)/solutions/$solutionId/': {
      id: '/(open)/solutions/$solutionId/'
      path: '/solutions/$solutionId'
      fullPath: '/solutions/$solutionId/'
      preLoaderRoute: typeof openSolutionsSolutionIdIndexRouteImport
      parentRoute: typeof openRouteRoute
    }
  }
}

interface openRouteRouteChildren {
  openPricingRoute: typeof openPricingRoute
  openIndexRoute: typeof openIndexRoute
  openProductsIndexRoute: typeof openProductsIndexRoute
  openSolutionsIndexRoute: typeof openSolutionsIndexRoute
  openProductsProductIdIndexRoute: typeof openProductsProductIdIndexRoute
  openSolutionsSolutionIdIndexRoute: typeof openSolutionsSolutionIdIndexRoute
}

const openRouteRouteChildren: openRouteRouteChildren = {
  openPricingRoute: openPricingRoute,
  openIndexRoute: openIndexRoute,
  openProductsIndexRoute: openProductsIndexRoute,
  openSolutionsIndexRoute: openSolutionsIndexRoute,
  openProductsProductIdIndexRoute: openProductsProductIdIndexRoute,
  openSolutionsSolutionIdIndexRoute: openSolutionsSolutionIdIndexRoute,
}

const openRouteRouteWithChildren = openRouteRoute._addFileChildren(
  openRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  openRouteRoute: openRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authSignUpRoute: authSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
