/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppWorkspaceIdIndexRouteImport } from './routes/app/$workspaceId/index'
import { Route as AppWorkspaceIdProjectsIndexRouteImport } from './routes/app/$workspaceId/projects/index'
import { Route as AppWorkspaceIdProjectsProjectIdRouteImport } from './routes/app/$workspaceId/projects/$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkspaceIdIndexRoute = AppWorkspaceIdIndexRouteImport.update({
  id: '/$workspaceId/',
  path: '/$workspaceId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkspaceIdProjectsIndexRoute =
  AppWorkspaceIdProjectsIndexRouteImport.update({
    id: '/$workspaceId/projects/',
    path: '/$workspaceId/projects/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppWorkspaceIdProjectsProjectIdRoute =
  AppWorkspaceIdProjectsProjectIdRouteImport.update({
    id: '/$workspaceId/projects/$projectId',
    path: '/$workspaceId/projects/$projectId',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/$workspaceId/': typeof AppWorkspaceIdIndexRoute
  '/app/$workspaceId/projects/$projectId': typeof AppWorkspaceIdProjectsProjectIdRoute
  '/app/$workspaceId/projects/': typeof AppWorkspaceIdProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppIndexRoute
  '/app/$workspaceId': typeof AppWorkspaceIdIndexRoute
  '/app/$workspaceId/projects/$projectId': typeof AppWorkspaceIdProjectsProjectIdRoute
  '/app/$workspaceId/projects': typeof AppWorkspaceIdProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/$workspaceId/': typeof AppWorkspaceIdIndexRoute
  '/app/$workspaceId/projects/$projectId': typeof AppWorkspaceIdProjectsProjectIdRoute
  '/app/$workspaceId/projects/': typeof AppWorkspaceIdProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/'
    | '/app/$workspaceId/'
    | '/app/$workspaceId/projects/$projectId'
    | '/app/$workspaceId/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/$workspaceId'
    | '/app/$workspaceId/projects/$projectId'
    | '/app/$workspaceId/projects'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/'
    | '/app/$workspaceId/'
    | '/app/$workspaceId/projects/$projectId'
    | '/app/$workspaceId/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/$workspaceId/': {
      id: '/app/$workspaceId/'
      path: '/$workspaceId'
      fullPath: '/app/$workspaceId/'
      preLoaderRoute: typeof AppWorkspaceIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/$workspaceId/projects/': {
      id: '/app/$workspaceId/projects/'
      path: '/$workspaceId/projects'
      fullPath: '/app/$workspaceId/projects/'
      preLoaderRoute: typeof AppWorkspaceIdProjectsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/$workspaceId/projects/$projectId': {
      id: '/app/$workspaceId/projects/$projectId'
      path: '/$workspaceId/projects/$projectId'
      fullPath: '/app/$workspaceId/projects/$projectId'
      preLoaderRoute: typeof AppWorkspaceIdProjectsProjectIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppWorkspaceIdIndexRoute: typeof AppWorkspaceIdIndexRoute
  AppWorkspaceIdProjectsProjectIdRoute: typeof AppWorkspaceIdProjectsProjectIdRoute
  AppWorkspaceIdProjectsIndexRoute: typeof AppWorkspaceIdProjectsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppWorkspaceIdIndexRoute: AppWorkspaceIdIndexRoute,
  AppWorkspaceIdProjectsProjectIdRoute: AppWorkspaceIdProjectsProjectIdRoute,
  AppWorkspaceIdProjectsIndexRoute: AppWorkspaceIdProjectsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
